# Generated by Django 6.0.3 on 2026-04-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='remarks',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late')], max_length=10),
        ),
    ]
