# Generated by Django 6.0.3 on 2026-04-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_student_user_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
