# Generated by Django 6.0.3 on 2026-04-26 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_proxy_role_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
        migrations.DeleteModel(
            name='StudentUser',
        ),
        migrations.DeleteModel(
            name='TeacherUser',
        ),
    ]
