# Generated by Django 6.0.3 on 2026-04-26 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_teacher_admin_remarks_recorded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrsession',
            name='subject',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'course', 'date')},
        ),
        migrations.AddField(
            model_name='course',
            name='class_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='core.classgroup'),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
